### ISSUE TITLE
client connect_and_activate panics without server

### ISSUE THREAD

**Issue by fr-ser** [locka99/opcua#31]
Hello,  firstly thanks for the tremendous work. I really appreciate it!

On the other hand I am really new with the OPC UA protocol as well as Rust itself. If the issue/question is a matter of my limited experience, sorry for that and feel free to close it any time.

**But to the issue:**
The sample client panics if no server is running (I would assume it should return an Err instead...)

Stacktrace:
```
"opc.tcp://127.0.0.1:4855/"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: <core::option::Option<T>>::unwrap
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:10
  10: opcua_client::message_queue::MessageQueue::add_request
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/message_queue.rs:43
  11: opcua_client::session_state::SessionState::add_request
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/session_state.rs:276
  12: opcua_client::session_state::SessionState::async_send_request
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/session_state.rs:229
  13: opcua_client::session_state::SessionState::send_request
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/session_state.rs:208
  14: opcua_client::session_state::SessionState::issue_or_renew_secure_channel
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/session_state.rs:317
  15: opcua_client::session::Session::open_secure_channel
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/session.rs:289
  16: opcua_client::session::Session::connect
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/session.rs:260
  17: opcua_client::client::Client::get_server_endpoints_from_url
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/client.rs:290
  18: opcua_client::client::Client::get_server_endpoints
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/client.rs:256
  19: opcua_client::client::Client::connect_and_activate
             at /home/sergej/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.5.0/src/client.rs:131
  20: opcua_reader::run
             at src/lib.rs:35
  21: opcua_reader::main
             at src/main.rs:18
  22: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  23: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  25: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  26: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  27: main
  28: __libc_start_main
  29: _start
```

**Comment by locka99** [comment]
Hi, I would need a working sample to understand what the cause of the issue might be.

The client API is much improved since 0.5 so I would recommend checking out the master and trying some of the samples to see if that makes things clearer. 0.6 should also be published shortly - perhaps within a week or so to crates.io. I'm just going through some last minute things.
