### ISSUE TITLE
Panic with very large requested_session_timeout

### ISSUE THREAD

**Issue by jsnnerve** [locka99/opcua#62]
Hi,

First of all, thank you for creating this library 💯 

I am trying to use a (slightly modified) simple-server to monitor some values on a server, however, the server seems to request an (unreasonably) long session timeout, which results in a panic.

$ RUST_BACKTRACE=1 RUST_OPCUA_LOG=debug ./client
2020-09-24 11:36:21.095 - INFO - opcua_console_logging - Logging is enabled, use RUST_OPCUA_LOG environment variable to control filtering, logging level
2020-09-24 11:36:21.096 - WARN - opcua_client::config - Endpoint config contains no endpoints
2020-09-24 11:36:21.108 - INFO - opcua_client::session - Connect
2020-09-24 11:36:21.109 - INFO - opcua_client::session - Security policy = None
2020-09-24 11:36:21.109 - INFO - opcua_client::session - Security mode = None
2020-09-24 11:36:21.109 - DEBUG - opcua_client::comms::tcp_transport - Connecting to "opc.tcp://192.168.1.100/"
2020-09-24 11:36:21.109 - DEBUG - opcua_client::comms::tcp_transport - Creating a connection task to connect to 192.168.1.100:4840 with url opc.tcp://192.168.1.100/
2020-09-24 11:36:21.110 - DEBUG - opcua_core::runtime - deregistering component connection-task, 1
2020-09-24 11:36:21.110 - DEBUG - opcua_client::comms::tcp_transport - Waiting for a connect (or failure to connect)
2020-09-24 11:36:21.111 - DEBUG - opcua_client::comms::tcp_transport - Client tokio tasks are starting for connection
2020-09-24 11:36:21.111 - DEBUG - opcua_core::runtime - deregistering component client-connection-thread-ThreadId(3)
2020-09-24 11:36:21.114 - DEBUG - tokio_reactor - adding I/O source: 0
2020-09-24 11:36:21.114 - DEBUG - tokio_reactor::registration - scheduling Write for: 0
2020-09-24 11:36:21.135 - DEBUG - opcua_client::comms::tcp_transport - Sending HELLO
2020-09-24 11:36:21.135 - DEBUG - opcua_core::runtime - deregistering component finished-monitor-task, 1
2020-09-24 11:36:21.135 - DEBUG - opcua_core::runtime - deregistering component read-task, 1
2020-09-24 11:36:21.136 - DEBUG - opcua_core::runtime - deregistering component write-task, 1
2020-09-24 11:36:21.137 - DEBUG - opcua_core::runtime - deregistering component connection-task, 1
2020-09-24 11:36:21.137 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.196 - DEBUG - opcua_client::comms::tcp_transport - Reader got ack AcknowledgeMessage { message_header: MessageHeader { message_type: Acknowledge, message_size: 28 }, protocol_version: 0, receive_buffer_size: 65536, send_buffer_size: 65536, max_message_size: 16777216, max_chunk_count: 1 }
2020-09-24 11:36:21.197 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.210 - DEBUG - opcua_client::comms::tcp_transport - Connected
2020-09-24 11:36:21.211 - DEBUG - opcua_client::session - session:1 open_secure_channel
2020-09-24 11:36:21.211 - INFO - opcua_client::session_state - Making secure channel request
2020-09-24 11:36:21.211 - INFO - opcua_client::session_state - security_mode = None
2020-09-24 11:36:21.211 - INFO - opcua_client::session_state - security_policy = None
2020-09-24 11:36:21.211 - DEBUG - opcua_client::comms::tcp_transport - About to write
2020-09-24 11:36:21.211 - DEBUG - opcua_core::comms::secure_channel - AsymmetricSecurityHeader = AsymmetricSecurityHeader { security_policy_uri: UAString { value: Some("http://opcfoundation.org/UA/SecurityPolicy#None") }, sender_certificate: ByteString { value: None }, receiver_certificate_thumbprint: ByteString { value: None } }
2020-09-24 11:36:21.212 - DEBUG - opcua_client::message_queue - Request 1 was processed by the server
2020-09-24 11:36:21.231 - DEBUG - opcua_client::message_queue - Response to Request 1 has been stored
2020-09-24 11:36:21.232 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.261 - DEBUG - opcua_client::session_state - Setting transport's security token
2020-09-24 11:36:21.261 - INFO - opcua_client::session - Connect was successful
2020-09-24 11:36:21.261 - DEBUG - opcua_client::session - session:1 get_endpoints
2020-09-24 11:36:21.262 - DEBUG - opcua_client::comms::tcp_transport - About to write
2020-09-24 11:36:21.262 - DEBUG - opcua_client::message_queue - Request 2 was processed by the server
2020-09-24 11:36:21.270 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.273 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.275 - DEBUG - opcua_client::message_queue - Response to Request 2 has been stored
2020-09-24 11:36:21.276 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.312 - DEBUG - opcua_client::session - session:1 get_endpoints, success
2020-09-24 11:36:21.312 - DEBUG - opcua_client::message_queue - Sending a quit to the message receiver
2020-09-24 11:36:21.312 - DEBUG - opcua_client::comms::tcp_transport - Waiting for a disconnect
2020-09-24 11:36:21.312 - DEBUG - opcua_client::comms::tcp_transport - About to write
2020-09-24 11:36:21.312 - DEBUG - opcua_client::comms::tcp_transport - Writer is about to send a CloseSecureChannelRequest which means it should close in a moment
2020-09-24 11:36:21.313 - DEBUG - opcua_client::message_queue - Request 3 was processed by the server
2020-09-24 11:36:21.313 - DEBUG - opcua_client::comms::tcp_transport - Writer is setting the connection state to finished(good)
2020-09-24 11:36:21.313 - DEBUG - opcua_client::comms::tcp_transport - Write bytes task received a close, so closing connection after this send
2020-09-24 11:36:21.313 - DEBUG - opcua_client::comms::tcp_transport - Writer loop is finished with an error
2020-09-24 11:36:21.313 - DEBUG - opcua_core::runtime - deregistering component write-task, 1
2020-09-24 11:36:21.313 - INFO - opcua_client::comms::tcp_transport - WriteState has dropped
2020-09-24 11:36:21.317 - DEBUG - tokio_reactor - dropping I/O source: 0
2020-09-24 11:36:21.317 - DEBUG - opcua_client::comms::tcp_transport - Read loop is terminating due to finished state
2020-09-24 11:36:21.318 - INFO - opcua_client::comms::tcp_transport - ReadState has dropped
2020-09-24 11:36:21.318 - DEBUG - opcua_client::comms::tcp_transport - Read loop ended with an error
2020-09-24 11:36:21.318 - DEBUG - opcua_core::runtime - deregistering component read-task, 1
2020-09-24 11:36:21.337 - DEBUG - opcua_client::comms::tcp_transport - finished monitor task detects finished state and has set a finished flag
2020-09-24 11:36:21.337 - INFO - opcua_client::comms::tcp_transport - Timer for finished is finished
2020-09-24 11:36:21.337 - DEBUG - opcua_core::runtime - deregistering component finished-monitor-task, 1
2020-09-24 11:36:21.338 - DEBUG - opcua_client::comms::tcp_transport - Client tokio tasks have stopped for connection
2020-09-24 11:36:21.338 - DEBUG - opcua_client::session_state - Session was closed with status = BadCommunicationError
2020-09-24 11:36:21.339 - DEBUG - opcua_core::runtime - deregistering component client-connection-thread-ThreadId(3)
2020-09-24 11:36:21.412 - DEBUG - opcua_client::comms::tcp_transport - Disconnected
2020-09-24 11:36:21.413 - INFO - opcua_client::session - Session has dropped
2020-09-24 11:36:21.413 - INFO - opcua_client::comms::tcp_transport - TcpTransport has dropped
2020-09-24 11:36:21.413 - INFO - opcua_client::subscription_timer - Timer receiver has terminated
2020-09-24 11:36:21.413 - INFO - opcua_client::session_state - SessionState has dropped
2020-09-24 11:36:21.414 - INFO - opcua_client::session - Connect
2020-09-24 11:36:21.415 - INFO - opcua_client::session - Security policy = None
2020-09-24 11:36:21.415 - INFO - opcua_client::session - Security mode = None
2020-09-24 11:36:21.416 - DEBUG - opcua_client::comms::tcp_transport - Connecting to "opc.tcp://br-automation:4840/"
2020-09-24 11:36:21.417 - DEBUG - opcua_client::comms::tcp_transport - Creating a connection task to connect to 192.168.1.100:4840 with url opc.tcp://br-automation:4840
2020-09-24 11:36:21.417 - DEBUG - opcua_core::runtime - deregistering component connection-task, 2
2020-09-24 11:36:21.418 - DEBUG - opcua_client::comms::tcp_transport - Waiting for a connect (or failure to connect)
2020-09-24 11:36:21.418 - DEBUG - opcua_client::comms::tcp_transport - Client tokio tasks are starting for connection
2020-09-24 11:36:21.418 - DEBUG - opcua_core::runtime - deregistering component client-connection-thread-ThreadId(11)
2020-09-24 11:36:21.421 - DEBUG - tokio_reactor - adding I/O source: 0
2020-09-24 11:36:21.421 - DEBUG - tokio_reactor::registration - scheduling Write for: 0
2020-09-24 11:36:21.422 - DEBUG - opcua_client::comms::tcp_transport - Sending HELLO
2020-09-24 11:36:21.423 - DEBUG - opcua_core::runtime - deregistering component finished-monitor-task, 2
2020-09-24 11:36:21.423 - DEBUG - opcua_core::runtime - deregistering component read-task, 2
2020-09-24 11:36:21.424 - DEBUG - opcua_core::runtime - deregistering component write-task, 2
2020-09-24 11:36:21.424 - DEBUG - opcua_core::runtime - deregistering component connection-task, 2
2020-09-24 11:36:21.425 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.429 - DEBUG - opcua_client::comms::tcp_transport - Reader got ack AcknowledgeMessage { message_header: MessageHeader { message_type: Acknowledge, message_size: 28 }, protocol_version: 0, receive_buffer_size: 65536, send_buffer_size: 65536, max_message_size: 16777216, max_chunk_count: 1 }
2020-09-24 11:36:21.430 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.518 - DEBUG - opcua_client::comms::tcp_transport - Connected
2020-09-24 11:36:21.518 - DEBUG - opcua_client::session - session:2 open_secure_channel
2020-09-24 11:36:21.519 - INFO - opcua_client::session_state - Making secure channel request
2020-09-24 11:36:21.519 - INFO - opcua_client::session_state - security_mode = None
2020-09-24 11:36:21.519 - INFO - opcua_client::session_state - security_policy = None
2020-09-24 11:36:21.519 - DEBUG - opcua_client::comms::tcp_transport - About to write
2020-09-24 11:36:21.519 - DEBUG - opcua_core::comms::secure_channel - AsymmetricSecurityHeader = AsymmetricSecurityHeader { security_policy_uri: UAString { value: Some("http://opcfoundation.org/UA/SecurityPolicy#None") }, sender_certificate: ByteString { value: None }, receiver_certificate_thumbprint: ByteString { value: None } }
2020-09-24 11:36:21.520 - DEBUG - opcua_client::message_queue - Request 1 was processed by the server
2020-09-24 11:36:21.526 - DEBUG - opcua_client::message_queue - Response to Request 1 has been stored
2020-09-24 11:36:21.526 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.569 - DEBUG - opcua_client::session_state - Setting transport's security token
2020-09-24 11:36:21.569 - INFO - opcua_client::session - Connect was successful
2020-09-24 11:36:21.570 - DEBUG - opcua_client::session - session:2 CreateSessionRequest = CreateSessionRequest { request_header: RequestHeader { authentication_token: NodeId { namespace: 0, identifier: Numeric(0) }, timestamp: DateTime { date_time: 2020-09-24T11:36:21.570578200Z }, request_handle: 2, return_diagnostics: (empty), audit_entry_id: UAString { value: None }, timeout_hint: 10000, additional_header: ExtensionObject { node_id: NodeId { namespace: 0, identifier: Numeric(0) }, body: None } }, client_description: ApplicationDescription { application_uri: UAString { value: Some("urn:MyFirstClient") }, product_uri: UAString { value: Some("") }, application_name: LocalizedText { locale: UAString { value: Some("") }, text: UAString { value: Some("My First Client") } }, application_type: Client, gateway_server_uri: UAString { value: None }, discovery_profile_uri: UAString { value: None }, discovery_urls: None }, server_uri: UAString { value: None }, endpoint_url: UAString { value: Some("opc.tcp://192.168.1.100:4840") }, session_name: UAString { value: Some("Rust OPCUA Client") }, client_nonce: ByteString { value: None }, client_certificate: ByteString { value: Some([ ### Shortened for brevity ### ]) }, requested_session_timeout: **179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.0,** max_response_message_size: 0 }
2020-09-24 11:36:21.571 - DEBUG - opcua_client::comms::tcp_transport - About to write
2020-09-24 11:36:21.572 - DEBUG - opcua_client::message_queue - Request 2 was processed by the server
2020-09-24 11:36:21.587 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.588 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.591 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.593 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.597 - DEBUG - opcua_client::message_queue - Response to Request 2 has been stored
2020-09-24 11:36:21.598 - DEBUG - tokio_reactor::registration - scheduling Read for: 0
2020-09-24 11:36:21.621 - DEBUG - opcua_client::session - session:2 Revised session timeout is 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2020-09-24 11:36:21.622 - DEBUG - opcua_client::session - session:2 spawn_session_activity_task(179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
thread 'main' panicked at 'attempt to multiply with overflow', /home/nss/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.7.0/src/session.rs:918:41
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:50
  14: opcua_client::session::Session::spawn_session_activity_task
             at /home/nss/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.7.0/src/session.rs:918
  15: opcua_client::session::Session::create_session
  16: opcua_client::session::Session::connect_and_activate
  17: opcua_client::client::Client::connect_to_endpoint
             at /home/nss/.cargo/registry/src/github.com-1ecc6299db9ec823/opcua-client-0.7.0/src/client.rs:236
  18: client::main
             at src/bin/client.rs:24
  19: std::rt::lang_start::{{closure}}
             at /home/nss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  22: std::panicking::try
             at src/libstd/panicking.rs:325
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: std::rt::lang_start
             at /home/nss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  26: main
  27: __libc_start_main
             at /build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2020-09-24 11:36:22.414 - INFO - opcua_client::session - Session has dropped
2020-09-24 11:36:22.414 - DEBUG - opcua_client::message_queue - Sending a quit to the message receiver
2020-09-24 11:36:22.414 - DEBUG - opcua_client::comms::tcp_transport - Waiting for a disconnect
2020-09-24 11:36:22.414 - DEBUG - opcua_client::comms::tcp_transport - About to write
2020-09-24 11:36:22.414 - DEBUG - opcua_client::comms::tcp_transport - Writer is about to send a CloseSecureChannelRequest which means it should close in a moment
2020-09-24 11:36:22.415 - DEBUG - opcua_client::message_queue - Request 3 was processed by the server
2020-09-24 11:36:22.415 - DEBUG - opcua_client::comms::tcp_transport - Writer is setting the connection state to finished(good)
2020-09-24 11:36:22.415 - DEBUG - opcua_client::comms::tcp_transport - Write bytes task received a close, so closing connection after this send
2020-09-24 11:36:22.415 - DEBUG - opcua_client::comms::tcp_transport - Writer loop is finished with an error
2020-09-24 11:36:22.415 - DEBUG - opcua_core::runtime - deregistering component write-task, 2
2020-09-24 11:36:22.415 - INFO - opcua_client::comms::tcp_transport - WriteState has dropped
2020-09-24 11:36:22.424 - DEBUG - opcua_client::comms::tcp_transport - finished monitor task detects finished state and has set a finished flag
2020-09-24 11:36:22.424 - INFO - opcua_client::comms::tcp_transport - Timer for finished is finished
2020-09-24 11:36:22.424 - DEBUG - opcua_core::runtime - deregistering component finished-monitor-task, 2
2020-09-24 11:36:22.476 - DEBUG - opcua_core::comms::tcp_codec - TcpCodec decode abort flag has been set and is terminating
2020-09-24 11:36:22.476 - ERROR - opcua_client::comms::tcp_transport - Read loop error Custom { kind: Other, error: "StatusCode BadOperationAbandoned" }
2020-09-24 11:36:22.476 - DEBUG - tokio_reactor - dropping I/O source: 0
2020-09-24 11:36:22.476 - INFO - opcua_client::comms::tcp_transport - ReadState has dropped
2020-09-24 11:36:22.476 - DEBUG - opcua_client::comms::tcp_transport - Read loop ended with an error
2020-09-24 11:36:22.476 - DEBUG - opcua_core::runtime - deregistering component read-task, 2
2020-09-24 11:36:22.477 - DEBUG - opcua_client::comms::tcp_transport - Client tokio tasks have stopped for connection
2020-09-24 11:36:22.477 - DEBUG - opcua_client::session_state - Session was closed with status = BadCommunicationError
2020-09-24 11:36:22.477 - DEBUG - opcua_core::runtime - deregistering component client-connection-thread-ThreadId(11)
2020-09-24 11:36:22.514 - DEBUG - opcua_client::comms::tcp_transport - Disconnected
2020-09-24 11:36:22.515 - INFO - opcua_client::comms::tcp_transport - TcpTransport has dropped
2020-09-24 11:36:22.515 - INFO - opcua_client::subscription_timer - Timer receiver has terminated
2020-09-24 11:36:22.515 - INFO - opcua_client::session_state - SessionState has dropped

**Comment by locka99** [comment]
I'll take a look at this to see if there is a way to make session timeout logic more bullet proof
